### PR TITLE
Add DICOM conformance statement

### PR DESCRIPTION
**Pull request by cgorman**
This PR includes the DICOM conformance statement written by Markus and converted by me to markdown. Pandoc handled about 80% of it but there were some things I needed to manually tweak (e.g. the definition list).

### CODE REVIEW

**Comment by CPBridge** [comment]
Looks good to me. I'm slightly confused by the first table: what is the "Study Service" row and why is it blank?

**Comment by fedorov** [comment]
Comments from @dclunie:
* add source for the figures
* include original source for completeness

**Comment by fedorov** [comment]
Let's link it from the readme/front page.

**Comment by cgorman** [comment]
@fedorov @dclunie @CPBridge OK I think I addressed your comments/concerns, let me know if there's anything else.

**Review by CPBridge — APPROVED** [review]

**Comment by CPBridge** [comment]
I think we should just merge this, we can always tweak later

**Review by fedorov — APPROVED** [review]

**Pull request merged**
