### PR TITLE
feat: add secondary dicom server

### PR DESCRIPTION
**Pull request by pedrokohler**
Adding the ability to use a secondary annotations server passed in the url with the gcp query parameter.

Solves https://github.com/ImagingDataCommons/slim/issues/186

Before: 

Only one server allowed.

After:

https://github.com/ImagingDataCommons/slim/assets/22822446/9c01d40d-04b6-4b8c-a9e6-b00a0d9f85dc

### CODE REVIEW

**Comment by igoroctaviano** [comment]
@pedrokohler instead of using it like:

http://localhost:3000/studies/2.25.68803095896966276583382138924964839274/series/1.3.6.1.4.1.5962.99.1.1163866303.1057408148.1637546438847.2.0?gcp=projects/idc-external-031/locations/us-central1/datasets/slim-bulk-ann-annotations/dicomStores/slim-bulk-ann-annotations/dicomWeb

Update it so we use like:

http://localhost:3000/studies/2.25.68803095896966276583382138924964839274/series/1.3.6.1.4.1.5962.99.1.1163866303.1057408148.1637546438847.2.0?gcp=https://healthcare.googleapis.com/v1beta1/projects/idc-external-031/locations/us-central1/datasets/tiled_full_vs_tiled_sparse/dicomStores/tiled_full_all/dicomWeb

**Review by igoroctaviano — CHANGES_REQUESTED** [review]
its working :) I left one comment.

**Comment by igoroctaviano** [comment]
@pedrokohler please address linting step which is failing

**Comment by pedrokohler** [comment]
> @pedrokohler please address linting step which is failing

@igoroctaviano done.

**Review by igoroctaviano — APPROVED** [review]
LGTM

**Pull request merged**
