### PR TITLE
Add new features available in upstream to this fork

### PR DESCRIPTION
**Pull request by hackermd**
@wlongabaugh this PR adds the features recently introduced into the *master* branch of *upstream* slim repo. Note that the new features to take effect, changes to the configuration will be necessary.

I'd recommend creating a separate `idc.js` configuration file instead of modifying the `local.js` (the latter is intended to work with the `Dockerfile` and `docker-compose.yml` configurations).

### CODE REVIEW

**Comment by hackermd** [comment]
@igoroctaviano do you know why the check fails? Should these tests even run in this fork?

**Comment by hackermd** [comment]
You want to use a configuration like this:

```javascript
window.config = {
  path: "/slim",
  servers: [
    {
      id: "idc",
      url: "",  // URL of DICOMweb proxy
      write: false
    }
  ],
  renderer:
  {
    retrieveRendered: false
  },
  annotations: [ ],
  disableWorklist: true,
  disableAnnotationTools: true
};
```

**Comment by igoroctaviano** [comment]
> @igoroctaviano do you know why the check fails? Should these tests even run in this fork?

Actually, the deploy failed because it's missing the firebase service acc.
`Error: Input required and not supplied: firebaseServiceAccount`
maybe something specific to IDC pipeline? @wlongabaugh

**Comment by hackermd** [comment]
> > @igoroctaviano do you know why the check fails? Should these tests even run in this fork?
> 
> Actually, the deploy failed because it's missing the firebase service acc.
> `Error: Input required and not supplied: firebaseServiceAccount`
> maybe something specific to IDC pipeline? @wlongabaugh

I think we only configured the application/action for the main slim repo, but not for the IDC fork.

**Comment by igoroctaviano** [comment]
> > > @igoroctaviano do you know why the check fails? Should these tests even run in this fork?
> > 
> > 
> > Actually, the deploy failed because it's missing the firebase service acc.
> > `Error: Input required and not supplied: firebaseServiceAccount`
> > maybe something specific to IDC pipeline? @wlongabaugh
> 
> I think we only configured the application/action for the main slim repo, but not for the IDC fork.

I think thats right, we need to migrate the firebase config files.

**Comment by wlongabaugh** [comment]
The viewer is built and deployed to a static bucket using our CircleCI build process. The firebase config files should not be triggered in IDC.

**Review by wlongabaugh — CHANGES_REQUESTED** [review]
I don't think the .github/workflows files (or .firebaserc) should be pulled into IDC master. We don't use firebase and my understanding is that these are going to trigger just by being present in the directory and having "on" conditions matching.

**Pull request merged**
