### PR TITLE
feat: improve annotation styles

### PR DESCRIPTION
**Pull request by pedrokohler**
Addresses

https://github.com/ImagingDataCommons/slim/issues/184#issuecomment-2452617344 (i.e.: fix unexpected color change when selecting annotations)
https://github.com/ImagingDataCommons/slim/issues/184#issuecomment-2468725056 (i.e.: add ability of using only outlines or showing filled annotations)
and
https://github.com/ImagingDataCommons/slim/issues/184#issuecomment-2468730362 (i.e.: add overlay of multiple annotations on hover)

### CODE REVIEW

**Review by igoroctaviano — CHANGES_REQUESTED** [review]
Please describe the changes in the PR, address sonarcube issue and if possible, add documentation to new methods.

**Comment by igoroctaviano** [comment]
> Please describe the changes in the PR, address sonarcube issue and if possible, add documentation to new methods.

@pedrokohler Also please update PR. I'll merge this PR and then cut a new release.

**Review by igoroctaviano — APPROVED** [review]
LGTM

**Comment by fedorov** [comment]
@pedrokohler could you please update the idc-slim fork with this?

**Pull request merged**
