### PR TITLE
fix: security issues

### PR DESCRIPTION
**Pull request by pedrokohler**
Fix all high and critical security issues listed in the file below:

[yarn-audit.txt](https://github.com/ImagingDataCommons/slim/files/13336303/yarn-audit-final.txt)

### CODE REVIEW

**Review by igoroctaviano — APPROVED** [review]
LGTM

**Comment by igoroctaviano** [comment]
@cgorman can u merge this one? the gh deploy is failing but I don't have permission to investigate. It's probably expired tokens.

**Comment by cgorman** [comment]
@igoroctaviano Hey sorry I also don't have the required permissions to do that. Maybe @fedorov can bump you to admin?

**Comment by fedorov** [comment]
Sorry for such a delay in responding. I missed the github notifications. Next time if I do not respond, please ping me on slack. I am getting too many notifications from github and things are falling through the cracks unfortunately.

**Pull request merged**
