### PR TITLE
feat: remove unused white space

### PR DESCRIPTION
**Pull request by pedrokohler**
Addresses: https://github.com/ImagingDataCommons/slim/issues/225

### CODE REVIEW

**Comment by fedorov** [comment]
Can you include a screenshot of how it looks with this change?

**Comment by pedrokohler** [comment]
> Can you include a screenshot of how it looks with this change?

Sure:

image

**Comment by fedorov** [comment]
Thank you. @ulrikew is this ok with you?

**Comment by ulrikew** [comment]
Can you please post an example where a patient has more than one slide?

**Comment by pedrokohler** [comment]
> Can you please post an example where a patient has more than one slide?

image

**Comment by ulrikew** [comment]
This looks great. Thank you for fixing this.

**Review by igoroctaviano — APPROVED** [review]
LGTM

**Pull request merged**
