### PR TITLE
Update dicom-microscopy-viewer dependency

### PR DESCRIPTION
**Pull request by cgorman**
Updates dicom-microscopy-viewer to 0.45.0 which fixes JPEG 2000 decoding errors

### CODE REVIEW

**Comment by cgorman** [comment]
Oh I guess we need to do similar mapping here that we did to make the DMV tests work. I'll get a fix pushed in a bit.

**Comment by fedorov** [comment]
@igoroctaviano can you take a glance at this? I do not think I can do a meaninfgul review.

**Review by igoroctaviano — APPROVED** [review]
LGTM

**Comment by cgorman** [comment]
It is preventing me from merging due to a "missing github-pages deployment", but the github-pages deployment ran successfully. I don't have admin rights, can somebody update the project settings? Maybe it is checking for the old herrmanlab.github.io URL or something.

**Comment by fedorov** [comment]
@cgorman I was able to merge!

**Comment by cgorman** [comment]
Great, thanks! I'll publish as a new release now

**Pull request merged**
